import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { api, type Org, type Session } from './api';
import './admin.css';

type Role = 'admin' | 'manager' | 'marketing' | 'sales' | 'csm';
type Member = { id: string; name: string; email: string; active: boolean; memberships: { id: string; role: Role; orgUnitId: string }[] };
type Pool = { id: string; name: string; orgUnitId: string; active: boolean; members: { userId: string }[] };
const roles: { id: Role; label: string; scope: string }[] = [
  { id: 'admin', label: '管理员', scope: '管理成员、组织和销售池；查看本租户业务' },
  { id: 'manager', label: '销售主管', scope: '管理本组织线索、客户与商机，审核线索转化' },
  { id: 'marketing', label: '线索运营', scope: '创建、分配线索并查看分配结果' },
  { id: 'sales', label: '销售', scope: '处理分配给自己的线索、客户、商机与跟进' },
  { id: 'csm', label: '客户服务', scope: '处理客户服务计划、任务与风险' },
];
const roleLabel = (id: string) => roles.find(role => role.id === id)?.label || id;
const pageSize = 15;

function Dialog({ title, close, children }: { title: string; close: () => void; children: ReactNode }) {
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === 'Escape') close(); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [close]);
  return <div className="admin-overlay" onMouseDown={close}><section className="admin-dialog" role="dialog" aria-modal="true" aria-label={title} onMouseDown={event => event.stopPropagation()}><div className="admin-dialog-head"><h2>{title}</h2><button type="button" onClick={close} aria-label="关闭">×</button></div>{children}</section></div>;
}

export function AdminPage({ session }: { session: Session }) {
  const [tab, setTab] = useState<'members' | 'roles' | 'pools' | 'orgs'>('members');
  const [members, setMembers] = useState<Member[]>([]); const [orgs, setOrgs] = useState<Org[]>([]); const [pools, setPools] = useState<Pool[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false);
  const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [dialog, setDialog] = useState<'member' | 'pool' | 'org' | null>(null);
  const [editPool, setEditPool] = useState<Pool | null>(null); const [editMember, setEditMember] = useState<Member | null>(null);
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState<Role>('sales');
  const [orgId, setOrgId] = useState(session.user.memberships[0]?.orgUnitId || ''); const [selected, setSelected] = useState<string[]>([]); const [memberQuery, setMemberQuery] = useState(''); const [poolActive, setPoolActive] = useState(true);
  async function refresh() { const [users, units, salesPools] = await Promise.all([api<Member[]>('/admin/users'), api<Org[]>('/org-units'), api<Pool[]>('/admin/lead-pools')]); setMembers(users); setOrgs(units); setPools(salesPools); if (!orgId && units[0]) setOrgId(units[0].id); }
  useEffect(() => { refresh().catch(cause => setError(cause instanceof Error ? cause.message : '加载失败')).finally(() => setLoading(false)); }, []);
  async function run(work: () => Promise<unknown>, message: string, close = true) { setBusy(true); setError(''); setSuccess(''); try { await work(); await refresh(); setSuccess(message); if (close) { setDialog(null); setEditMember(null); setEditPool(null); } } catch (cause) { setError(cause instanceof Error ? cause.message : '操作失败'); } finally { setBusy(false); } }
  const filtered = useMemo(() => members.filter(item => `${item.name} ${item.email}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [members, query]);
  const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  const orgName = (id: string) => orgs.find(org => org.id === id)?.name || '未命名组织';
  const sales = members.filter(item => item.active && item.memberships.some(m => m.role === 'sales' && m.orgUnitId === orgId));
  const candidates = sales.filter(item => `${item.name} ${item.email}`.toLocaleLowerCase().includes(memberQuery.trim().toLocaleLowerCase()));
  function openNewPool() { setEditPool(null); setName(''); setOrgId(orgs[0]?.id || ''); setSelected([]); setPoolActive(true); setMemberQuery(''); setDialog('pool'); }
  function openPool(pool: Pool) { setEditPool(pool); setName(pool.name); setOrgId(pool.orgUnitId); setSelected(pool.members.map(item => item.userId)); setPoolActive(pool.active); setMemberQuery(''); setDialog('pool'); }
  function openMember() { setName(''); setEmail(''); setPassword(''); setRole('sales'); setOrgId(orgs[0]?.id || ''); setDialog('member'); }
  async function createMember(event: FormEvent) { event.preventDefault(); await run(() => api('/admin/users', { method: 'POST', body: { name, email, password, role, org_unit_id: orgId } }), '成员已创建'); }
  async function savePool(event: FormEvent) { event.preventDefault(); if (!selected.length) { setError('请选择至少一位在职销售'); return; } await run(() => api(editPool ? `/admin/lead-pools/${editPool.id}` : '/admin/lead-pools', { method: editPool ? 'PATCH' : 'POST', body: editPool ? { name, active: poolActive, user_ids: selected } : { name, org_unit_id: orgId, user_ids: selected } }), editPool ? '销售池已更新' : '销售池已创建'); }
  async function createOrg(event: FormEvent) { event.preventDefault(); await run(() => api('/admin/org-units', { method: 'POST', body: { name } }), '组织已创建'); }
  async function changeRole(member: Member, membershipId: string, next: Role) { if (!window.confirm(`将 ${member.name} 的角色改为${roleLabel(next)}？该成员需要重新登录。`)) return; await run(() => api(`/admin/users/${member.id}/membership`, { method: 'PATCH', body: { membership_id: membershipId, role: next } }), '角色已更新'); }
  async function changeActive(member: Member) { const next = !member.active; if (!window.confirm(`${next ? '启用' : '停用'} ${member.name}？${next ? '' : '停用后该成员会退出登录。'}`)) return; await run(() => api(`/admin/users/${member.id}/active`, { method: 'PATCH', body: { active: next } }), next ? '成员已启用' : '成员已停用', false); }
  return <div className="admin-page"><div className="page-header"><div className="page-title-wrap"><div><h1>系统管理</h1></div></div></div>
    <div className="admin-tabs" role="tablist" aria-label="系统管理">{[['members','成员'],['roles','角色与权限'],['pools','线索分配池'],['orgs','组织']] .map(([id,label]) => <button key={id} type="button" role="tab" aria-selected={tab === id} className={tab === id ? 'active' : ''} onClick={() => { setTab(id as typeof tab); setError(''); }}>{label}</button>)}</div>
    {error && <div className="notice error" role="alert">{error}</div>}{success && <div className="notice success" role="status">{success}</div>}{loading && <div className="loading">正在加载…</div>}
    {!loading && tab === 'members' && <section className="panel admin-panel"><div className="admin-panel-head"><div><h2>成员</h2><span>{members.length} 人</span></div><button className="button primary" onClick={openMember}>新增成员</button></div><input className="admin-search" value={query} onChange={event => { setQuery(event.target.value); setPage(1); }} placeholder="搜索姓名或邮箱" aria-label="搜索成员"/>
      {visible.length ? <div className="admin-member-list">{visible.map(member => <div className="admin-member" key={member.id}><span className="admin-member-avatar">{member.name.slice(0,1)}</span><div className="admin-member-main"><strong>{member.name}</strong><small>{member.email}</small><div className="admin-member-roles">{member.memberships.map(m => <span key={m.id}>{orgName(m.orgUnitId)} · {roleLabel(m.role)}</span>)}</div></div><span className={`admin-status ${member.active ? '' : 'inactive'}`}>{member.active ? '在职' : '已停用'}</span><button className="button secondary compact" onClick={() => setEditMember(member)}>设置角色</button><button className="button secondary compact" disabled={member.id === session.user.id} onClick={() => changeActive(member)}>{member.active ? '停用' : '启用'}</button></div>)}</div> : <div className="admin-empty">没有符合条件的成员</div>}
      {filtered.length > pageSize && <div className="admin-pager"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>上一页</button><span>{page} / {Math.ceil(filtered.length / pageSize)}</span><button disabled={page * pageSize >= filtered.length} onClick={() => setPage(page + 1)}>下一页</button></div>}</section>}
    {!loading && tab === 'roles' && <section className="panel admin-panel"><div className="admin-panel-head"><div><h2>角色与权限</h2><span>角色权限按业务规则执行</span></div><button className="button secondary" onClick={() => setTab('members')}>为成员设置角色</button></div><div className="admin-role-list">{roles.map(item => <div key={item.id}><strong>{item.label}</strong><p>{item.scope}</p><span>{members.filter(member => member.active && member.memberships.some(m => m.role === item.id)).length} 位在职成员</span></div>)}</div></section>}
    {!loading && tab === 'pools' && <section className="panel admin-panel"><div className="admin-panel-head"><div><h2>线索分配池</h2><span>分配线索时，可从同组织的销售中按顺序轮转</span></div><button className="button primary" onClick={openNewPool}>新建分配池</button></div>{pools.length ? <div className="admin-pool-list">{pools.map(pool => <div key={pool.id}><div><strong>{pool.name}</strong><span>{orgName(pool.orgUnitId)} · {pool.members.length} 位销售 · {pool.active ? '启用' : '停用'}</span><small>{pool.members.map(item => members.find(member => member.id === item.userId)?.name || '未知成员').join('、')}</small></div><button className="button secondary compact" onClick={() => openPool(pool)}>管理成员与状态</button></div>)}</div> : <div className="admin-empty">暂无分配池。新建后可在线索详情中使用轮转分配。</div>}</section>}
    {!loading && tab === 'orgs' && <section className="panel admin-panel"><div className="admin-panel-head"><div><h2>组织</h2><span>{orgs.length} 个组织</span></div><button className="button primary" onClick={() => { setName(''); setDialog('org'); }}>新增组织</button></div><div className="admin-org-list">{orgs.map(org => <div key={org.id}><strong>{org.name}</strong><span>{members.filter(member => member.memberships.some(m => m.orgUnitId === org.id)).length} 位成员</span></div>)}</div></section>}
    {dialog === 'member' && <Dialog title="新增成员" close={() => setDialog(null)}><form className="admin-form" onSubmit={createMember}><label>姓名<input value={name} onChange={event => setName(event.target.value)} required/></label><label>邮箱<input type="email" value={email} onChange={event => setEmail(event.target.value)} required/></label><label>初始密码（至少 12 位）<input type="password" autoComplete="new-password" minLength={12} value={password} onChange={event => setPassword(event.target.value)} required/></label><label>角色<select value={role} onChange={event => setRole(event.target.value as Role)}>{roles.map(item => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>组织<select value={orgId} onChange={event => setOrgId(event.target.value)}>{orgs.map(org => <option value={org.id} key={org.id}>{org.name}</option>)}</select></label><div className="admin-form-actions"><button type="button" className="button secondary" onClick={() => setDialog(null)}>取消</button><button className="button primary" disabled={busy || !orgId}>创建成员</button></div></form></Dialog>}
    {editMember && <Dialog title={`设置角色 · ${editMember.name}`} close={() => setEditMember(null)}><div className="admin-role-editor">{editMember.memberships.map(m => <label key={m.id}>{orgName(m.orgUnitId)}<select value={m.role} onChange={event => changeRole(editMember, m.id, event.target.value as Role)} disabled={busy}>{roles.map(item => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label>)}</div><p className="admin-dialog-hint">保存后，该成员的当前登录会话失效，需要重新登录。</p></Dialog>}
    {dialog === 'pool' && <Dialog title={editPool ? '管理分配池' : '新建分配池'} close={() => setDialog(null)}><form className="admin-form" onSubmit={savePool}><label>名称<input value={name} onChange={event => setName(event.target.value)} required/></label><label>所属组织<select value={orgId} disabled={Boolean(editPool)} onChange={event => { setOrgId(event.target.value); setSelected([]); }}>{orgs.map(org => <option value={org.id} key={org.id}>{org.name}</option>)}</select></label><div className="admin-field-title">轮转销售 <span>已选 {selected.length} 人</span></div><input className="admin-search" placeholder="按姓名或邮箱搜索" value={memberQuery} onChange={event => setMemberQuery(event.target.value)} aria-label="搜索轮转销售"/><div className="admin-candidates">{candidates.length ? candidates.map(member => <label key={member.id}><input type="checkbox" checked={selected.includes(member.id)} onChange={event => setSelected(event.target.checked ? [...selected, member.id] : selected.filter(id => id !== member.id))}/><span><strong>{member.name}</strong><small>{member.email}</small></span></label>) : <p>该组织没有符合条件的在职销售</p>}</div>{editPool && <label className="admin-switch"><input type="checkbox" checked={poolActive} onChange={event => setPoolActive(event.target.checked)}/>启用该分配池</label>}<div className="admin-form-actions"><button type="button" className="button secondary" onClick={() => setDialog(null)}>取消</button><button className="button primary" disabled={busy || !selected.length}>{editPool ? '保存修改' : '创建分配池'}</button></div></form></Dialog>}
    {dialog === 'org' && <Dialog title="新增组织" close={() => setDialog(null)}><form className="admin-form" onSubmit={createOrg}><label>组织名称<input value={name} onChange={event => setName(event.target.value)} required/></label><div className="admin-form-actions"><button type="button" className="button secondary" onClick={() => setDialog(null)}>取消</button><button className="button primary" disabled={busy}>创建组织</button></div></form></Dialog>}
  </div>;
}
